# This is a basic workflow to help you get started with Actions

name: Varios Jobs Entrelzados

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  extrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: ls .
  transformar: 
    runs-on: ubutu-lastest
    needs: extrate
    steps:
      - run: echo 'Hola Mundo'
      

     
